### ISSUE TITLE
Applicants and HRs can check the specific analysis generated with ChatGPT.

### ISSUE THREAD

**Issue by kang-theo** [kang-theo/ARM-Issues#2]
### Description
Applicant and HR can check the specific analysis generated with ChatGPT.
---

### Steps
For **Applicant**:
1. Go to **Dashboard** or "My Applications", view the match info for each job description, where the applicant can check the specific analysis result of ChatGPT.
![image](https://github.com/user-attachments/assets/8d4bb3f3-3dbb-4e3c-a935-1d8afc37c047)

For **HR**:
1. Go to **Applications**, view all the applications, where HR can check the specific analysis result for each applicant.
![image](https://github.com/user-attachments/assets/756f69d8-42e1-433a-a0f4-50641ad236f7)

**Comment by dongtong** [comment]
@kang-theo Added this feat
