### ISSUE TITLE
Dashborad for HR improvement

### ISSUE THREAD

**Issue by kang-theo** [kang-theo/ARM-Issues#4]
### Description
HRs focus on some metrics and statistics of applications, applicants, popularity of jobs, range of salary, etc. So it's better to have a standalone dashboard which is different from that of Applicants.
![image](https://github.com/user-attachments/assets/3e88d307-09b4-4bbb-b44e-c111d057379f)

**Comment by dongtong** [comment]
@kang-theo This is applicants' dashboard, I will create dashboard for HR Role.

**Comment by dongtong** [comment]
@kang-theo Current HR dashboard was updated

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/45de7adb-ad98-47f4-8da2-a8fa6640f551" />
