### ISSUE TITLE
Cannot update JD status

### ISSUE THREAD

**Issue by kang-theo** [kang-theo/ARM-Issues#5]
### Description
The fields are not filled with data in database when editing, which caused the update failure.
![image](https://github.com/user-attachments/assets/e368bbc3-81d4-4618-8741-cdf3c4d6d648)

When clicking "Update":
![image](https://github.com/user-attachments/assets/909b145d-663b-4b89-98a6-b6e1f37b8be4)

### Expected Behaviour
Just to change the status from "Open" to "Draft", then click "Update", the JD will be in a "Draft" status.

**Comment by dongtong** [comment]
@kang-theo I think this issue was resolved, please verify and close it. Thanks
